/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hsae_bowin_java2c1_NativeC */

#ifndef _Included_com_hsae_bowin_java2c1_NativeC
#define _Included_com_hsae_bowin_java2c1_NativeC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hsae_bowin_java2c1_NativeC
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_hsae_bowin_java2c1_NativeC_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_hsae_bowin_java2c1_NativeC
 * Method:    getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hsae_bowin_java2c1_NativeC_getString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_hsae_bowin_java2c1_NativeC
 * Method:    GetArray
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_hsae_bowin_java2c1_NativeC_GetArray
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
