/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hsae_bowin_c2java_C2java */

#ifndef _Included_com_hsae_bowin_c2java_C2java
#define _Included_com_hsae_bowin_c2java_C2java
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hsae_bowin_c2java_C2java
 * Method:    callbackAdd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hsae_bowin_c2java_C2java_callbackAdd
  (JNIEnv *, jobject);

/*
 * Class:     com_hsae_bowin_c2java_C2java
 * Method:    callbackFormJava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hsae_bowin_c2java_C2java_callbackFormJava
  (JNIEnv *, jobject);

/*
 * Class:     com_hsae_bowin_c2java_C2java
 * Method:    callbackPrintString
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hsae_bowin_c2java_C2java_callbackPrintString
  (JNIEnv *, jobject);

/*
 * Class:     com_hsae_bowin_c2java_C2java
 * Method:    callbackSayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hsae_bowin_c2java_C2java_callbackSayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
