/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hsae_bowin_ndkdemo_JNIUtils */

#ifndef _Included_com_hsae_bowin_ndkdemo_JNIUtils
#define _Included_com_hsae_bowin_ndkdemo_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hsae_bowin_ndkdemo_JNIUtils
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hsae_bowin_ndkdemo_JNIUtils_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
